let prayersAboutHealth = [
  {
    id: 1,
    title: "Prayer for Healing",
    content:
      "Lord, You invite all who are burdened to come to you. Allow Your healing Hand to heal me. Touch my soul with Your compassion for others. Touch my heart with Your courage and infinite Love for all. Touch my mind with Your Wisdom, that my mouth may always proclaim Your praise. Teach me to reach out to You in all my needs, and help me to lead others to You by my example. Most loving Heart of Jesus, bring me health in body and spirit that I may serve You with all my strength. Touch gently this life which you have created, now and forever. Amen.",
    category: "Health",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
  {
    id: 2,
    title: "Prayer for Healing",
    content:
      "Lord, look upon me with eyes of mercy, may your healing hand rest upon me, may your lifegiving powers flow into every cell of my body and into the depths of my soul, cleansing, purifying, restoring me to wholeness and strength for service in your Kingdom. Amen.",
    category: "Health",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
  {
    id: 3,
    title: "Prayer for Healing",
    content:
      "Lord, you are the same yesterday, today and forever. In your love and mercy, please come to my help and give me the grace to place my trust in you. I ask this in the name of Jesus. Amen.",
    category: "Health",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
  {
    id: 4,
    title: "Prayer for Healing",
    content:
      "Lord, you are the same yesterday, today and forever. In your love and mercy, please come to my help and give me the grace to place my trust in you. I ask this in the name of Jesus. Amen.",
    category: "Health",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
  {
    id: 5,
    title: "Prayer for Healing",
    content:
      "Lord, you are the same yesterday, today and forever. In your love and mercy, please come to my help and give me the grace to place my trust in you. I ask this in the name of Jesus. Amen.",
    category: "Health",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
];

module.exports = prayersAboutHealth;
