let warfarePrayers = [
  {
    id: 1,
    title: "Warfare Prayers",
    content: "Warfare Prayer 1",
    category: "Wealth",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
  {
    id: 2,
    title: "Warfare Prayers",
    content: "Warfare Prayer 2",
    category: "Wealth",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
  {
    id: 3,
    title: "Warfare Prayers",
    content: "Warfare Prayer 3",
    category: "Wealth",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
  {
    id: 4,
    title: "Warfare Prayers",
    content: "Warfare Prayer 4",
    category: "Wealth",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
  {
    id: 5,
    title: "Warfare Prayers",
    content: "Warfare Prayer 5",
    category: "Wealth",
    scripture: "Matthew 11:28-30",
    date: "2021-01-01",
    time: "12:00:00",
    archived: false,
    answered: false,
    answeredDate: null,
    answeredTime: null,
    answeredContent: null,
  },
];

module.exports = warfarePrayers;
